export const advisors = [
  {
    id: "adv-alex",
    name: "Alex Lim",
    role: "Advisor",
    region: "Klang Valley",
    licenseStatus: "Active",
    cpdHours: 18,
    cpdTarget: 30,
    riskProfile: "normal",
    focusSegments: ["HNW Family Office", "SME Owner", "Professional"],
    languages: ["English", "Bahasa Malaysia", "Mandarin"],
    bookPremium: 162000,
    retentionRate: 94,
    referralsWon: 7,
  },
  {
    id: "adv-maya",
    name: "Maya Singh",
    role: "Advisor",
    region: "Penang",
    licenseStatus: "Active",
    cpdHours: 26,
    cpdTarget: 30,
    riskProfile: "normal",
    focusSegments: ["Young Family", "Professional"],
    languages: ["English", "Bahasa Malaysia", "Tamil"],
    bookPremium: 98000,
    retentionRate: 91,
    referralsWon: 4,
  },
  {
    id: "admin-nadia",
    name: "Nadia Wong",
    role: "Admin",
    region: "Malaysia",
    licenseStatus: "Admin",
    cpdHours: 0,
    cpdTarget: 0,
    riskProfile: "oversight",
    focusSegments: ["Governance", "Operations"],
    languages: ["English", "Bahasa Malaysia", "Mandarin"],
    bookPremium: 0,
    retentionRate: 0,
    referralsWon: 0,
  },
];

export const clients = [
  {
    id: "client-tan",
    name: "Mr. Tan Chee Wei",
    segment: "HNW Family Office",
    age: 58,
    occupation: "Manufacturing Founder",
    location: "Petaling Jaya",
    advisorId: "adv-alex",
    prioritySignals: ["Policy review overdue", "Recent liquidity event", "Estate planning gap"],
    needs: ["legacy", "key-person", "medical", "tax"],
    assets: "RM 8.2m",
    annualPremium: 86000,
    lastContact: "2026-06-11",
    nextMeeting: "2026-06-20T10:30:00",
    consentStatus: "Verified",
    household: "Spouse and two adult children",
    propensity: 92,
    estimatedCoverageGap: 1800000,
    nextBestOffer: "Estate liquidity bridge with key-person continuity review",
    policyValue: 128000,
    opportunityValue: 480000,
    referralPotential: 96,
    engagementUrgency: 88,
    careUrgency: 96,
    relationshipImportance: 98,
    personality: "Decisive founder who prefers concise options and practical next steps",
    interests: ["golf", "single-origin coffee", "succession planning", "family travel"],
    preferredChannel: "WhatsApp",
    preferredTone: "Concise and warm",
    telegramChatId: "",
    telegramOptIn: false,
    birthday: "1968-06-20",
    lifeEvent: "Birthday today and daughter starts university in Australia in July",
    relationshipNotes: "Strong VIP relationship; open with birthday care, coffee and golf, then keep the estate review to a one-page decision path.",
    memory: [
      "Prefers concise WhatsApp summaries before calls.",
      "Daughter starts university in Australia in July.",
      "Enjoys Saturday golf at Saujana and asks for coffee recommendations.",
      "Asked about succession planning after factory expansion.",
      "Sensitive to long product decks; wants one-page options.",
    ],
    timeline: [
      { date: "2026-06-20", type: "Meeting", note: "Annual portfolio and estate review scheduled." },
      { date: "2026-06-12", type: "Signal", note: "Sold minority stake in Tan Precision Components." },
      { date: "2026-05-28", type: "Service", note: "Updated beneficiary nomination for medical plan." },
      { date: "2026-04-19", type: "Referral", note: "Introduced to ASG tax desk for holding structure review." },
    ],
  },
  {
    id: "client-aisha",
    name: "Dr. Aisha Rahman",
    segment: "Professional",
    age: 41,
    occupation: "Cardiologist",
    location: "Subang Jaya",
    advisorId: "adv-alex",
    prioritySignals: ["New clinic partnership", "Protection shortfall", "High income volatility"],
    needs: ["medical", "income", "business"],
    assets: "RM 1.7m",
    annualPremium: 34000,
    lastContact: "2026-06-17",
    nextMeeting: "2026-06-20T14:00:00",
    consentStatus: "Verified",
    household: "Single, supports parents",
    propensity: 84,
    estimatedCoverageGap: 950000,
    nextBestOffer: "Specialist income protection and clinic buy-in continuity plan",
    policyValue: 54000,
    opportunityValue: 180000,
    referralPotential: 72,
    engagementUrgency: 74,
    careUrgency: 62,
    relationshipImportance: 82,
    personality: "Analytical specialist who likes evidence, benchmarks and clear assumptions",
    interests: ["medical innovation", "parent care", "data dashboards"],
    preferredChannel: "Email",
    preferredTone: "Evidence-led",
    telegramChatId: "",
    telegramOptIn: false,
    birthday: "1985-09-14",
    lifeEvent: "Considering buying into a private clinic group",
    relationshipNotes: "Keep messages structured with benchmarks and clear personal-versus-clinic separation.",
    memory: [
      "Values data-led comparisons and peer benchmarks.",
      "Considering buying into a private clinic group.",
      "Prefers email follow-ups after 8pm.",
      "Wants scenarios that separate personal cover from clinic liabilities.",
    ],
    timeline: [
      { date: "2026-06-20", type: "Meeting", note: "Clinic partnership protection discussion." },
      { date: "2026-06-14", type: "Note", note: "Asked for disability income scenarios." },
      { date: "2026-05-08", type: "CPD", note: "Advisor completed medical specialist planning module." },
      { date: "2026-04-22", type: "Claim", note: "Asked about specialist panel access for parents." },
    ],
  },
  {
    id: "client-lee",
    name: "Consent-locked client",
    segment: "Consent Hold",
    age: null,
    occupation: "Masked",
    location: "Masked",
    advisorId: "adv-alex",
    prioritySignals: ["Consent review due", "Private signals masked"],
    needs: ["consent-review"],
    assets: "Masked",
    annualPremium: 0,
    lastContact: "2026-06-05",
    nextMeeting: "2026-06-21T11:30:00",
    consentStatus: "Review due",
    household: "Masked",
    propensity: 0,
    estimatedCoverageGap: 0,
    nextBestOffer: "Refresh PDPA consent before any recommendation",
    policyValue: 0,
    opportunityValue: 0,
    referralPotential: 0,
    engagementUrgency: 0,
    careUrgency: 0,
    relationshipImportance: 0,
    personality: "Masked",
    interests: [],
    preferredChannel: "Masked",
    preferredTone: "Consent-safe",
    telegramChatId: "",
    telegramOptIn: false,
    birthday: null,
    lifeEvent: "Masked",
    relationshipNotes: "Private relationship intelligence remains masked until consent refresh.",
    memory: [
      "Private record masked until consent refresh.",
      "Advisor must verify consent before reviewing notes.",
    ],
    timeline: [
      { date: "2026-06-21", type: "Compliance", note: "Consent refresh pending." },
      { date: "2026-06-07", type: "Task", note: "Consent refresh requested." },
    ],
  },
  {
    id: "client-kumar",
    name: "Mr. Kumar Nair",
    segment: "SME Owner",
    age: 49,
    occupation: "Logistics Director",
    location: "Shah Alam",
    advisorId: "adv-alex",
    prioritySignals: ["Missed premium", "Fleet expansion loan", "Key-person concentration"],
    needs: ["key-person", "debt", "medical"],
    assets: "RM 2.9m",
    annualPremium: 42000,
    lastContact: "2026-05-30",
    nextMeeting: null,
    consentStatus: "Verified",
    household: "Spouse, three children, family-owned logistics firm",
    propensity: 78,
    estimatedCoverageGap: 1250000,
    nextBestOffer: "Debt protection reset tied to fleet financing facility",
    policyValue: 68000,
    opportunityValue: 220000,
    referralPotential: 64,
    engagementUrgency: 91,
    careUrgency: 86,
    relationshipImportance: 74,
    personality: "Direct operator who values practical, low-admin fixes",
    interests: ["logistics tech", "early breakfast meetings", "football"],
    preferredChannel: "Phone",
    preferredTone: "Direct and practical",
    telegramChatId: "",
    telegramOptIn: false,
    birthday: "1977-11-03",
    lifeEvent: "Fleet expansion loan has increased guarantor exposure",
    relationshipNotes: "Lead with service recovery before any relationship gesture because a missed premium signal is active.",
    memory: [
      "Prefers calls before 9am.",
      "Concerned about loan covenant exposure.",
      "Wants practical, low-admin solutions.",
      "Responds well to risk maps by vehicle, route and guarantor.",
    ],
    timeline: [
      { date: "2026-06-18", type: "Alert", note: "Premium reminder generated after missed payment." },
      { date: "2026-06-03", type: "Signal", note: "New fleet financing facility announced." },
      { date: "2026-05-18", type: "Service", note: "Group medical claims analysis completed." },
      { date: "2026-04-02", type: "Referral", note: "Introduced to SME Risk Solutions for debt cover design." },
    ],
  },
  {
    id: "client-nurul",
    name: "Ms. Nurul Iman",
    segment: "Young Family",
    age: 34,
    occupation: "Product Manager",
    location: "Cyberjaya",
    advisorId: "adv-maya",
    prioritySignals: ["Newborn added", "Mortgage approved", "Education goal opened"],
    needs: ["family", "education", "medical"],
    assets: "RM 620k",
    annualPremium: 18500,
    lastContact: "2026-06-16",
    nextMeeting: "2026-06-22T09:00:00",
    consentStatus: "Verified",
    household: "Married with newborn",
    propensity: 73,
    estimatedCoverageGap: 620000,
    nextBestOffer: "Family protection starter plan with education funding pathway",
    policyValue: 28500,
    opportunityValue: 95000,
    referralPotential: 58,
    engagementUrgency: 69,
    careUrgency: 78,
    relationshipImportance: 80,
    personality: "Busy product leader who wants transparent, staged decisions",
    interests: ["newborn care", "education planning", "productivity apps"],
    preferredChannel: "In-app message",
    preferredTone: "Friendly and clear",
    telegramChatId: "",
    telegramOptIn: false,
    birthday: "1992-02-18",
    lifeEvent: "Newborn added and first family mortgage approved",
    relationshipNotes: "Offer flexible options and make space for spouse alignment before any product recommendation.",
    memory: [
      "Prefers app messages during work hours.",
      "Asked for joint affordability view with spouse.",
      "Wants transparent fees and flexible premium options.",
    ],
    timeline: [
      { date: "2026-06-19", type: "Signal", note: "Mortgage approval imported from planning checklist." },
      { date: "2026-06-15", type: "Life event", note: "Newborn dependent added to household profile." },
      { date: "2026-05-30", type: "Goal", note: "Education funding goal created." },
    ],
  },
  {
    id: "client-sofia",
    name: "Ms. Sofia Chong",
    segment: "Tech Entrepreneur",
    age: 37,
    occupation: "SaaS Founder",
    location: "Bangsar",
    advisorId: "adv-alex",
    prioritySignals: ["Series A term sheet", "Key-person dependency", "US expansion planning"],
    needs: ["business", "key-person", "income", "tax"],
    assets: "RM 3.6m",
    annualPremium: 52000,
    lastContact: "2026-06-13",
    nextMeeting: null,
    consentStatus: "Verified",
    household: "Married, no children, co-founder equity concentration",
    propensity: 81,
    estimatedCoverageGap: 1120000,
    nextBestOffer: "Founder continuity and cross-border income protection review",
    policyValue: 78000,
    opportunityValue: 260000,
    referralPotential: 88,
    engagementUrgency: 82,
    careUrgency: 72,
    relationshipImportance: 86,
    personality: "Fast-moving founder who values sharp options and founder peer examples",
    interests: ["trail running", "specialty tea", "startup mentoring"],
    preferredChannel: "WhatsApp",
    preferredTone: "Sharp and encouraging",
    telegramChatId: "",
    telegramOptIn: false,
    birthday: "1989-06-26",
    lifeEvent: "Series A term sheet expected by end of June",
    relationshipNotes: "Keep suggestions compact and tie them to founder runway, equity concentration and hiring risk.",
    memory: [
      "Prefers two options with trade-offs, not long comparisons.",
      "Mentors first-time founders on Friday afternoons.",
      "Asked whether US expansion changes protection design.",
    ],
    timeline: [
      { date: "2026-06-18", type: "Signal", note: "Investor diligence checklist requested continuity evidence." },
      { date: "2026-06-13", type: "Note", note: "Discussed co-founder dependency and hiring runway." },
      { date: "2026-05-21", type: "Referral", note: "Introduced to tax desk for US entity planning." },
    ],
  },
  {
    id: "client-farid",
    name: "Encik Farid Ismail",
    segment: "Retirement Planning",
    age: 62,
    occupation: "Semi-retired Engineer",
    location: "Ipoh",
    advisorId: "adv-maya",
    prioritySignals: ["Retirement income review", "Grandchild education promise"],
    needs: ["retirement", "education", "medical"],
    assets: "RM 980k",
    annualPremium: 14600,
    lastContact: "2026-06-01",
    nextMeeting: null,
    consentStatus: "Verified",
    household: "Married, supports one grandchild education goal",
    propensity: 59,
    estimatedCoverageGap: 360000,
    nextBestOffer: "Retirement income and medical reserve check",
    policyValue: 21000,
    opportunityValue: 52000,
    referralPotential: 34,
    engagementUrgency: 58,
    careUrgency: 67,
    relationshipImportance: 64,
    personality: "Patient and detail-oriented; prefers calm explanations",
    interests: ["gardening", "grandchild education", "community volunteering"],
    preferredChannel: "Phone",
    preferredTone: "Calm and respectful",
    telegramChatId: "",
    telegramOptIn: false,
    birthday: "1964-07-02",
    lifeEvent: "Grandchild education pledge was added to retirement plan",
    relationshipNotes: "Use plain language and avoid rushing; focus on reassurance and income stability.",
    memory: [
      "Prefers phone calls after lunch.",
      "Asked to include spouse in retirement decisions.",
      "Values conservative assumptions and written summaries.",
    ],
    timeline: [
      { date: "2026-06-11", type: "Goal", note: "Grandchild education pledge added." },
      { date: "2026-06-01", type: "Review", note: "Medical reserve concern discussed." },
      { date: "2026-05-02", type: "Service", note: "Updated nominee contact details." },
    ],
  },
];

export const meetings = [
  { id: "mtg-1", clientId: "client-tan", time: "10:30", topic: "Estate and liquidity review", channel: "Office" },
  { id: "mtg-2", clientId: "client-aisha", time: "14:00", topic: "Clinic partnership protection", channel: "Teams" },
  { id: "mtg-3", clientId: "client-lee", time: "Tomorrow 11:30", topic: "Consent refresh pending", channel: "Masked" },
  { id: "mtg-4", clientId: "client-nurul", time: "Monday 09:00", topic: "Young family protection review", channel: "Video" },
  { id: "mtg-5", clientId: "client-sofia", time: "Tuesday 16:30", topic: "Founder continuity planning", channel: "WhatsApp" },
];

export const tasks = [
  {
    id: "task-1",
    clientId: "client-tan",
    title: "Prepare one-page legacy planning options",
    due: "2026-06-20",
    status: "Open",
    severity: "high",
  },
  {
    id: "task-2",
    clientId: "client-kumar",
    title: "Resolve missed premium and debt cover gap",
    due: "2026-06-18",
    status: "Overdue",
    severity: "high",
  },
  {
    id: "task-3",
    clientId: "client-lee",
    title: "Refresh PDPA consent before recommendation",
    due: "2026-06-19",
    status: "Overdue",
    severity: "medium",
  },
  {
    id: "task-4",
    clientId: "client-aisha",
    title: "Send disability income benchmark scenarios",
    due: "2026-06-20",
    status: "Open",
    severity: "medium",
  },
  {
    id: "task-5",
    clientId: "client-nurul",
    title: "Build joint affordability view for family protection",
    due: "2026-06-21",
    status: "Open",
    severity: "medium",
  },
  {
    id: "task-6",
    clientId: "client-tan",
    title: "Confirm tax desk availability before meeting",
    due: "2026-06-20",
    status: "Open",
    severity: "medium",
  },
  {
    id: "task-7",
    clientId: "client-sofia",
    title: "Prepare founder continuity options before Series A term sheet",
    due: "2026-06-21",
    status: "Open",
    severity: "high",
  },
  {
    id: "task-8",
    clientId: "client-farid",
    title: "Call after lunch about retirement income and medical reserve",
    due: "2026-06-18",
    status: "Overdue",
    severity: "medium",
  },
];

export const overnightSignals = [
  { id: "sig-1", source: "CRM", clientId: "client-tan", signal: "Liquidity event", confidence: 96, action: "Prepare legacy options" },
  { id: "sig-2", source: "Billing", clientId: "client-kumar", signal: "Missed premium", confidence: 99, action: "Prevent lapse" },
  { id: "sig-3", source: "Consent ledger", clientId: "client-lee", signal: "Consent expired", confidence: 100, action: "Mask private data" },
  { id: "sig-4", source: "Advisor note", clientId: "client-aisha", signal: "Clinic buy-in", confidence: 88, action: "Draft income scenarios" },
  { id: "sig-5", source: "Life event checklist", clientId: "client-nurul", signal: "Newborn and mortgage", confidence: 91, action: "Recommend family review" },
  { id: "sig-6", source: "CRM", clientId: "client-sofia", signal: "Series A diligence", confidence: 93, action: "Prepare founder continuity brief" },
  { id: "sig-7", source: "Advisor note", clientId: "client-tan", signal: "Birthday golf coffee moment", confidence: 97, action: "Send relationship care note" },
];

export const advisorKpis = [
  { id: "kpi-1", advisorId: "adv-alex", label: "Next-best-action acceptance", value: 78, unit: "%", target: 72, trend: "+9 pts" },
  { id: "kpi-2", advisorId: "adv-alex", label: "Client response within 24h", value: 86, unit: "%", target: 80, trend: "+6 pts" },
  { id: "kpi-3", advisorId: "adv-alex", label: "Consent-safe recommendations", value: 100, unit: "%", target: 100, trend: "On target" },
  { id: "kpi-4", advisorId: "adv-alex", label: "CPD completion", value: 60, unit: "%", target: 100, trend: "12 hours left" },
  { id: "kpi-5", advisorId: "adv-maya", label: "Young-family conversion", value: 64, unit: "%", target: 58, trend: "+6 pts" },
];

export const businessImpact = [
  { id: "impact-1", label: "Premium protected", value: 128000, unit: "RM", narrative: "At-risk premium surfaced before lapse or review delay." },
  { id: "impact-2", label: "Estimated coverage gap found", value: 4620000, unit: "RM", narrative: "Needs-based gaps identified across verified clients." },
  { id: "impact-3", label: "Advisor admin time saved", value: 9.5, unit: "hours/week", narrative: "Briefing, matching, CPD and audit summaries automated offline." },
  { id: "impact-4", label: "Referral revenue pipeline", value: 74000, unit: "RM", narrative: "Partner-ready opportunities routed to AAG x ASG specialists." },
  { id: "impact-5", label: "Compliance blocks enforced", value: 3, unit: "cases", narrative: "Consent and disclosure issues stopped before action." },
];

export const referralStages = [
  { id: "stage-1", name: "Detected", description: "Signal or need identified by AdvisorFlow AI.", sort: 1 },
  { id: "stage-2", name: "Qualified", description: "Advisor validates consent, suitability and client intent.", sort: 2 },
  { id: "stage-3", name: "Partner matched", description: "Best-fit AAG/ASG partner selected with reason and SLA.", sort: 3 },
  { id: "stage-4", name: "Submitted", description: "Referral created and audit logged.", sort: 4 },
  { id: "stage-5", name: "Outcome captured", description: "Revenue, service result and compliance evidence recorded.", sort: 5 },
];

export const referralOutcomes = [
  {
    id: "ref-seed-1",
    clientId: "client-tan",
    partnerId: "partner-tax",
    stage: "Partner matched",
    status: "In progress",
    expectedValue: 42000,
    probability: 82,
    note: "Tax and estate sequencing after liquidity event.",
  },
  {
    id: "ref-seed-2",
    clientId: "client-kumar",
    partnerId: "partner-sme",
    stage: "Qualified",
    status: "Advisor review",
    expectedValue: 21000,
    probability: 67,
    note: "Debt cover reset tied to fleet loan covenant.",
  },
  {
    id: "ref-seed-3",
    clientId: "client-aisha",
    partnerId: "partner-health",
    stage: "Detected",
    status: "Needs scenario",
    expectedValue: 11000,
    probability: 58,
    note: "Specialist underwriting and income protection benchmark.",
  },
];

export const complianceQueue = [
  {
    id: "comp-1",
    clientId: "client-lee",
    owner: "Nadia Wong",
    issue: "Consent refresh required before private data access",
    severity: "High",
    status: "Open",
    due: "2026-06-20",
    control: "Mask profile, block referrals and block expenses.",
  },
  {
    id: "comp-2",
    clientId: "client-kumar",
    owner: "Alex Lim",
    issue: "Missed premium communication must include lapse disclosure",
    severity: "Medium",
    status: "Review",
    due: "2026-06-20",
    control: "Draft message must include service-first language.",
  },
  {
    id: "comp-3",
    clientId: "client-tan",
    owner: "Alex Lim",
    issue: "Legacy proposal requires suitability rationale",
    severity: "Medium",
    status: "Ready",
    due: "2026-06-21",
    control: "Attach needs, liquidity event and beneficiary context.",
  },
  {
    id: "comp-4",
    clientId: "client-aisha",
    owner: "Nadia Wong",
    issue: "Medical scenario comparisons require balanced wording",
    severity: "Low",
    status: "Ready",
    due: "2026-06-22",
    control: "Avoid guaranteed-outcome language.",
  },
];

export const adminReviewItems = [
  {
    id: "review-1",
    title: "Consent refresh evidence pending",
    owner: "Nadia Wong",
    clientId: "client-lee",
    queue: "Compliance",
    priority: "High",
    eta: "Today",
  },
  {
    id: "review-2",
    title: "Flagged client follow-up claim visible",
    owner: "Nadia Wong",
    clientId: "client-tan",
    queue: "Expenses",
    priority: "Medium",
    eta: "1 day",
  },
  {
    id: "review-3",
    title: "Partner referral evidence pack visible",
    owner: "Nadia Wong",
    clientId: "client-tan",
    queue: "Referral",
    priority: "Medium",
    eta: "2 days",
  },
  {
    id: "review-4",
    title: "Monitor CPD shortfall for Advisor Alex",
    owner: "Nadia Wong",
    clientId: null,
    queue: "Training",
    priority: "Low",
    eta: "This week",
  },
];

export const cpdCourses = [
  {
    id: "cpd-legacy",
    title: "Estate Liquidity and Legacy Conversations",
    category: "Wealth Continuity",
    hours: 3,
    fitTags: ["legacy", "tax"],
    status: "Recommended",
    format: "Scenario lab",
    outcome: "Document suitability rationale for liquidity-triggered estate reviews.",
  },
  {
    id: "cpd-sme",
    title: "SME Key-Person and Debt Protection",
    category: "Business Protection",
    hours: 2,
    fitTags: ["key-person", "business", "debt"],
    status: "Recommended",
    format: "Case clinic",
    outcome: "Map debt, guarantor and key-person exposure into an advice note.",
  },
  {
    id: "cpd-medical",
    title: "Medical Specialist Planning Playbook",
    category: "Professional Segment",
    hours: 2,
    fitTags: ["medical", "income"],
    status: "Completed",
    format: "Microlearning",
    outcome: "Benchmark specialist income and disability scenarios.",
  },
  {
    id: "cpd-compliance",
    title: "Suitability, Consent and Audit Hygiene",
    category: "Compliance",
    hours: 1,
    fitTags: ["consent", "audit"],
    status: "Required",
    format: "Assessment",
    outcome: "Apply PDPA masking, disclosure and audit-log controls.",
  },
  {
    id: "cpd-family",
    title: "Young Family Needs Discovery",
    category: "Protection Planning",
    hours: 2,
    fitTags: ["family", "education", "medical"],
    status: "Recommended",
    format: "Guided roleplay",
    outcome: "Turn life-event signals into affordable staged recommendations.",
  },
];

export const partners = [
  {
    id: "partner-tax",
    name: "ASG Tax Advisory Desk",
    specialty: "Holding structures and tax planning",
    tags: ["tax", "legacy", "business"],
    sla: "1 business day",
    qualityScore: 94,
    availability: "2 senior advisors available today",
    evidenceRequired: ["Liquidity event note", "Entity structure", "Client consent"],
    commercialModel: "Referral fee eligible",
  },
  {
    id: "partner-estate",
    name: "AAG Estate Concierge",
    specialty: "Will, trust and beneficiary coordination",
    tags: ["legacy", "education", "family"],
    sla: "2 business days",
    qualityScore: 91,
    availability: "Next slot Monday morning",
    evidenceRequired: ["Beneficiary list", "Asset snapshot", "Family objective"],
    commercialModel: "Client-paid advisory package",
  },
  {
    id: "partner-health",
    name: "Premier Medical Underwriting",
    specialty: "Complex medical underwriting",
    tags: ["medical", "income"],
    sla: "4 hours",
    qualityScore: 89,
    availability: "Underwriter on call",
    evidenceRequired: ["Medical declaration", "Occupation profile", "Income range"],
    commercialModel: "Panel service",
  },
  {
    id: "partner-sme",
    name: "SME Risk Solutions",
    specialty: "Debt, fleet and key-person risk",
    tags: ["key-person", "debt", "business"],
    sla: "1 business day",
    qualityScore: 87,
    availability: "Risk analyst available after 3pm",
    evidenceRequired: ["Loan amount", "Guarantor list", "Business continuity concern"],
    commercialModel: "Referral fee eligible",
  },
  {
    id: "partner-education",
    name: "AAG Education Funding Desk",
    specialty: "Education savings and overseas tuition planning",
    tags: ["education", "family", "legacy"],
    sla: "2 business days",
    qualityScore: 86,
    availability: "Two planning slots this week",
    evidenceRequired: ["Child age", "Target country", "Monthly affordability"],
    commercialModel: "Planning support",
  },
];

export const expensesSeed = [
  {
    id: "exp-1",
    advisorId: "adv-alex",
    clientId: "client-tan",
    category: "Client meeting",
    amount: 128,
    status: "Approved",
    date: "2026-06-11",
  },
  {
    id: "exp-2",
    advisorId: "adv-alex",
    clientId: "client-aisha",
    category: "Parking",
    amount: 16,
    status: "Pending",
    date: "2026-06-17",
  },
  {
    id: "exp-3",
    advisorId: "adv-alex",
    clientId: "client-lee",
    category: "Claim masked",
    amount: null,
    status: "Masked",
    date: "2026-06-05",
  },
  {
    id: "exp-4",
    advisorId: "adv-alex",
    clientId: "client-kumar",
    category: "SME site visit",
    amount: 142,
    status: "Flagged",
    date: "2026-06-18",
  },
];

export const auditLogsSeed = [
  { id: "audit-1", time: "08:05", actor: "Alex Lim", action: "Viewed Mr. Tan client memory", risk: "Low" },
  { id: "audit-2", time: "08:12", actor: "AdvisorFlow AI", action: "Generated morning priority brief", risk: "Low" },
  { id: "audit-3", time: "08:18", actor: "Alex Lim", action: "Created ASG Tax Advisory referral", risk: "Medium" },
  {
    id: "audit-4",
    time: "08:21",
    actor: "System",
    action: "Blocked export until consent refresh for consent-locked client",
    risk: "High",
  },
  {
    id: "audit-5",
    time: "08:24",
    actor: "AdvisorFlow AI",
    action: "Scored compliance queue and highlighted lapse disclosure risk",
    risk: "Medium",
  },
  {
    id: "audit-6",
    time: "08:31",
    actor: "Nadia Wong",
    action: "Reviewed partner referral evidence checklist",
    risk: "Low",
  },
];
